package main

import "fmt"

func printTheory() {
	fmt.Println("╔══════════════════════════════════════════════════════════╗")
	fmt.Println("║          TOPIC: Hello World                               ║")
	fmt.Println("╚══════════════════════════════════════════════════════════╝")
	fmt.Println()
	fmt.Println("📚 THEORY")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("📦 PACKAGE DECLARATION")
	fmt.Println("   Every Go file starts with: package <name>")
	fmt.Println("   • package main = executable program")
	fmt.Println("   • Other packages (like package fmt) = libraries")
	fmt.Println("   • Package name determines what can be accessed")
	fmt.Println()
	fmt.Println("🚪 THE MAIN FUNCTION")
	fmt.Println("   Every executable Go program must have:")
	fmt.Println("   func main() { ... }")
	fmt.Println("   • func = keyword to define a function")
	fmt.Println("   • main = entry point (Go starts here)")
	fmt.Println("   • () = no parameters")
	fmt.Println("   • {} = function body")
	fmt.Println()
	fmt.Println("📥 IMPORTS")
	fmt.Println("   To use code from other packages:")
	fmt.Println("   import \"fmt\"")
	fmt.Println("   • import brings in functionality")
	fmt.Println("   • \"fmt\" = format package (for printing)")
	fmt.Println("   • Multiple imports can be grouped")
	fmt.Println()
	fmt.Println("🖨️  PRINTING OUTPUT")
	fmt.Println("   The fmt package provides:")
	fmt.Println("   • fmt.Println() - prints and adds newline")
	fmt.Println("   • fmt.Print() - prints without newline")
	fmt.Println("   • fmt.Printf() - formatted printing")
	fmt.Println()
	fmt.Println("▶️  RUNNING GO PROGRAMS")
	fmt.Println("   • go run main.go - compile and run in one step")
	fmt.Println("   • go build main.go - compile to binary")
	fmt.Println()
}

func exampleBasic() {
	fmt.Println("🔧 PRACTICAL EXAMPLES")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("Example: Basic Hello World")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("Code:")
	fmt.Println("  package main")
	fmt.Println("  import \"fmt\"")
	fmt.Println("  func main() {")
	fmt.Println("      fmt.Println(\"Hello, World!\")")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("What happens:")
	fmt.Println("  1. Declares package main (executable program)")
	fmt.Println("  2. Imports fmt package (for printing)")
	fmt.Println("  3. Defines main function (entry point)")
	fmt.Println("  4. Prints \"Hello, World!\" to console")
	fmt.Println()
	fmt.Println("Output:")
	fmt.Print("  ")
	fmt.Println("Hello, World!")
	fmt.Println()
}

func exampleMultiplePrints() {
	fmt.Println("Example: Multiple Print Statements")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("Code:")
	fmt.Println("  fmt.Print(\"Hello, \")")
	fmt.Println("  fmt.Print(\"World!\")")
	fmt.Println("  fmt.Println()")
	fmt.Println()
	fmt.Println("What happens:")
	fmt.Println("  • fmt.Print() doesn't add newline")
	fmt.Println("  • Multiple prints on same line")
	fmt.Println("  • fmt.Println() adds newline at end")
	fmt.Println()
	fmt.Print("  Output: ")
	fmt.Print("Hello, ")
	fmt.Print("World!")
	fmt.Println()
	fmt.Println()
}

func exampleFormattedPrint() {
	fmt.Println("Example: Formatted Printing with fmt.Printf")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("Code:")
	fmt.Println("  name := \"Go\"")
	fmt.Println("  version := 1.21")
	fmt.Println("  fmt.Printf(\"Language: %s, Version: %.2f\\n\", name, version)")
	fmt.Println()
	fmt.Println("What happens:")
	fmt.Println("  • %s = string placeholder")
	fmt.Println("  • %.2f = float with 2 decimal places")
	fmt.Println("  • \\n = newline character")
	fmt.Println()
	name := "Go"
	version := 1.21
	fmt.Print("  Output: ")
	fmt.Printf("Language: %s, Version: %.2f\n", name, version)
	fmt.Println()
}

func main() {
	printTheory()
	exampleBasic()
	exampleMultiplePrints()
	exampleFormattedPrint()
}
